name: pickmeup_dashboard
description: "Administracion para Menu com"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.55

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.2.1
  image_picker: ^1.1.1
  pu_material:
    path: ./pu_material
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  shared_preferences: ^2.2.3
  svg_flutter: ^0.0.1
  textfield_tags: ^3.0.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/logo/
    - pubspec.yaml

  fonts:
    - family: Sansation-bold
      fonts:
        - asset: fonts/Sansation_Bold.ttf
          weight: 700
        - asset: fonts/Sansation_Light.ttf
          weight: 300
        - asset: fonts/Sansation_Regular.ttf
          style: normal
